default:
  serverbase:       ''
# if you need to authenticate on your fhir server, set username and password
  username:        xxxx
  password:        xxxx
## TRUE = peer verification anschalten, FALSE = peer verification ausschalten   
  ssl_verify_peer: FALSE
  
 